import { atom } from 'recoil';
import { ENV } from '@utils/env';
import { IProfile } from '@utils/type';

export const initialProfile: IProfile = {
  id: 0,
  account_branch: null,
  account_name: null,
  account_number: null,
  bank: 0,
  active: false,
  username: '',
  full_name: '',
  first_name: '',
  last_name: '',
  ref_user_id: 0,
  referred_code: '',
  is_kyc_verified: false,
  created_at: '',
  updated_at: '',
  identification_number: null,
  identification_created_at: null,
  identification_created_from: null,
  identification_after_img: '',
  identification_befor_img: '',
  status_kyc: '',
  profile_img: '',
  image_bill: '',
  phone_number: '',
  avatar: '',
  address: '',
  province: '',
  district: '',
  district_id: 0,
  province_id: 0,
  company_level: 0,
  date_ykc: '',
  level: 0,
  code: '',
  dist: {
    id: 0,
    name: '',
  },
  prov: {
    id: 0,
    name: '',
  },
  company_level_info: {
    level_name: '',
    min_kpi: 0,
    commission: 0,
    f1_qualified: 0,
  },
  info: {
    id: 0,
    address: '',
    aff_link: '',
    agency: 0,
    birthday: '',
    code: '',
    email: '' || null,
    is_email_verified: false,
    is_phone_verified: false,
    phone: '',
    name: '',
    level: 0,
    kyc_state: 0,
  },
  wallet: {
    nal: 0,
    nft: 0,
    rena: 0,
    token: '' || null,
    total: 0,
    usd: 0,
    loca: 0,
    loca_bonus: 0,
    loca_bonus_extra: 0,
    loca_bonus_extra_compare_loca_bonus: 0,
  },
  wallet_company: {
    nal: 0,
    nft: 0,
    rena: 0,
    token: '' || null,
    total: 0,
    usd: 0,
    loca: 0,
    loca_bonus: 0,
    loca_bonus_extra: 0,
    loca_bonus_extra_compare_loca_bonus: 0,
  },
};

export const profileAtom = atom({
  key: `${ENV.LOCAL_STORAGE_KEY}_PROFILE`,
  default: {
    ...initialProfile,
  },
});
