# run-name: Deploy to ${{ github.event_name }} by @${{ github.actor }}

# on:
#   push:
#     branches:
#       - dev
#     tags:
#       - v*

# jobs:
#   cancel:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Cancel Previous Runs
#         uses: styfle/cancel-workflow-action@0.9.1
#         with:
#           access_token: ${{ github.token }}
#   deploy:
#     needs: cancel
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           username: ${{ secrets.SSH_USER_NAME }}
#           passphrase: ${{ secrets.SSH_PASS_PHRASE }}
#           port: 22
#           script_stop: true
#           script: |
#             cd ~/workspace/Next-Review/
#             ${{ secrets.GHP }}
#             npm install
#             npm run build
#             pm2 restart 0
            
#       - name: On Failure
#         if: failure()
#         uses: sarisia/actions-status-discord@v1
#         with:
#           webhook: ${{ secrets.DISCORD_URL }}

#   notifification:
#     needs: deploy
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read

#     steps:
#       - uses: sarisia/actions-status-discord@v1
#         if: always()
#         with:
#           webhook: ${{ secrets.DISCORD_URL }}
#           title: "Merge to branch master => auto deploy"
#           description: "Test for: hunglv.online"

# name: Daily Reminder

# on:
#   schedule:
#     - cron: "55 10 * * 1-5"
#   workflow_dispatch:

# jobs:
#   notifification:
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     steps:
#         - uses: sarisia/actions-status-discord@v1
#         if: always()
#         with:
#           webhook: ${{ secrets.DISCORD_URL }}
#           status: ${{ job.status }}
#           content: "Hey Anh Chị Em"
#           title: "deploy"
#           description: "Nhớ log time nhé <33"
#           image: ${{ secrets.AVATAR_URL }}
#           color: 0x0000ff
#           url: "https://github.com/sarisia/actions-status-discord"
#           username: GitHub Actions
#           avatar_url: ${{ secrets.AVATAR_URL }}


name: Daily Reminder

on:
  push:
    branches:
      - dev
    tags:
      - v*
  schedule:
    - cron: '32 13 * * *'
  workflow_dispatch:

jobs:
  notifification:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_URL }}
          status: ${{ job.status }}
          content: "Hey Anh Chị Em Nhớ Log Time nhé <33"
          title: "Release"
          description: "Nhớ log time nhé <33"
          image: ${{ secrets.AVATAR_URL }}
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}


